language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
 
env:
  - SYMFONY_VERSION=2.6.* PACKAGE_VERSION=high

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.3.* PACKAGE_VERSION=high
    - php: 5.6
      env: SYMFONY_VERSION=2.5.* PACKAGE_VERSION=high
    - php: 5.3.3
      env: SYMFONY_VERSION=2.3.* PACKAGE_VERSION=low
  allow_failures:
    - php: 5.6
      env: SYMFONY_VERSION=2.7.* PACKAGE_VERSION=high
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*@dev PACKAGE_VERSION=high
    - php: nightly

before_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - if [[ "$PACKAGE_VERSION" == "high" ]]; then composer update --prefer-source; fi
  - if [[ "$PACKAGE_VERSION" == "low" ]]; then composer update --prefer-lowest --prefer-source; fi
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
